### PR TITLE
Test for #56 - encode/decode

### PR DESCRIPTION
**Pull request by GearsAD**

### CODE REVIEW

**Comment by tkoolen** [comment]
Thanks. I really don't think we should add a recursive test dependency though. Also JSON shouldn't be necessary, I don't think. If you can get rid of those dependencies, this would be a good type of test to add.

**Comment by GearsAD** [comment]
Fair, I'll take a look tonight and try remove - agreed, it's a lot for a single test case.

**Comment by GearsAD** [comment]
I also moved the image_metadata_t struct to the test folder so that the tests don't add another dependency.

**Comment by tkoolen** [comment]
Excellent, thanks!

**Comment by tkoolen** [comment]
(Oops, a little premature, let's hope CI passes).

**Pull request merged**
